### ISSUE TITLE
Ejecutar script Windows10

### ISSUE THREAD

**Issue by sapomuyverde** [UniversoLibreMexicoAC/descargar-cfdi#1]
Hola,

Intentando ejecutar el script en Windows10 64bits, Python 3.5, seguí las indicaciones del readme.md
1-pip install -r requirements.txt
2-RFC/CIEC en credenciales.conf
3- ejecutar el script de la forma: descarga-cfdi -f c:\FELIPELUGO -fi 1/1/2014 -ff 31/12/2015
-f para establecer la carpeta en donde deseo se descarguen los archivos xml y -fi para fecha inicial y -ff para fecha final en el formato indicado de D/M/AAAA

Despliega esta salida que no entiendo:
![image](https://cloud.githubusercontent.com/assets/15135396/14940044/581154cc-0f29-11e6-9007-3f43d9552f2a.png)

Que estoy haciendo mal?.

Gracias.

Saludos,
Javier

**Comment by mauriciobaeza** [comment]
Posiblemente, estes usando la rama incorrecta... si miras el error, hace una llamada a admin_cfdi-0.3.0, esta versión del script NO usa estos scripts, son una rama y desarrollo separado, aun no tienen ni un setup...

Descarga la siguiente rama: https://github.com/UniversoLibreMexicoAC/descargar-cfdi/tree/script
y prueba de nuevo... si tienes instalado previamente admin-cfdi, es necesario uses un entorno virtual separado, o desinstala previamente admin-cfdi, recomendación, usa un entorno virtual.

Por otra parte, considera que esta rama esta desarrollada, por ahora, exclusivamente para Linux, no se como se comporte en Windows.

Saludos

**Comment by mauriciobaeza** [comment]
He probado la rama **develop** desde Windows 10 de forma exitosa...

Es indispensable, como admin, instalar los requerimientos...

    pip install -r requirements.txt

Despues ya puedes ejecutar con:

    python descarga-cfdi -rfc XAXX010101000 -ciec LETMEIN

**Comment by sapomuyverde** [comment]
Mauricio,

Como bien me comentaste, admin-cfdi estaba causando conflictos, he probado también de forma exitosa, por otro lado la opción LETMEIN sustituye la opción -f para el tema del folder?.

Saludos,
Javier

**Comment by mauriciobaeza** [comment]
No compañero... LETMEIN es solo un ejemplo de la contraseña para la ciec

    python descarga-cfdi -rfc XAXX010101000 -ciec AQUI_TU_CONTRASEÑA

Todo lo demas, como dice la documentacion
