### ISSUE TITLE
recomendación

### ISSUE THREAD

**Issue by AndyChiu** [UniversoLibreMexicoAC/descargar-cfdi#2]
Hola, se pueden aumentar mas opciones (parámetros) para mas más flexible?

-RFC
-CIEC
los dos se puede reemplazar -s , si no quiero guardar contraseña en texto y quiero usa con otro programas, asi es mejor opcion.

-LOG
se puede guardar archivo log en difurente carpeta y nombre por difurente trabajo.

Gracias!

**Comment by mauriciobaeza** [comment]
No entiendo la primera opción, si usas **-s** te solicita los datos al ejecutar para que no se guarden... o... ¿te refieres a agregar los parámetros para poder pasarlos, para que puedas llamarlo desde otro programa?

Compañero, tienes todo el código ahí para hacer los cambios que quieras, para hacer esto mira aquí: 
https://github.com/UniversoLibreMexicoAC/descargar-cfdi/blob/develop/descargacfdi/settings.py#L9
y aqui:
https://github.com/UniversoLibreMexicoAC/descargar-cfdi/blob/develop/descargacfdi/util.py#L32

Saludos

**Comment by AndyChiu** [comment]
si, quiero llamarlo desde otro programa , estoy pensando, si pueden usa commando como : 

"descarga-cfdi.py -a 2016 -m 04 -f d:\CFDI\2016\04\ -log d:\CFDI\2016\04.Log -RFC 1234567890ABC -CIEC test "

un commando puedo cuardar log difurente carpeta y nombre por difurente trabajo, y usa difurente RFC y CIEC para trabajo, no guardar contraseña en texto ,pienso mas securo.

si no usa opcion -log , automatico usar default en settings.py 

Gracias su programa y su responde, mi espanol no es muy bueno, y gracias su tiempo.

**Comment by mauriciobaeza** [comment]
you can use english, if is better for you
Puedes usar ingles si es mejor para ti...

Agregar esas opciones es fácil, lo verifico y te aviso por aquí...

**Comment by AndyChiu** [comment]
Usted muy amable! Gracias!

**Comment by mauriciobaeza** [comment]
Listo, prueba la rama **develop** con estos cambios...

En cuanto valides cerramos este issue

Puedes ejecutar desde Windows con
    
    python descarga-cfdi -rfc XAXX010101000 -ciec LETMEIN -log %HOMEPATH%/cfdi.log
